export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_PAGE_SIZE: 5,
  MAX_PAGE_SIZE: 100,
  MIN_PAGE_SIZE: 1,
};

export const LIMITS = {
  FREE_INTERVIEWS: 2,
  FREE_PRACTICE: 2,
  FREE_INTERVIEW_LIMIT_MINUTES: 30,
  PRO_INTERVIEWS: Infinity,
  PRO_PRACTICE: Infinity,
  PRO_INTERVIEW_LIMIT_MINUTES: 60,
}