export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_PAGE_SIZE: 5,
  MAX_PAGE_SIZE: 100,
  MIN_PAGE_SIZE: 1,
};

export const LIMITS = {
  FREE_INTERVIEWS: 2,
  FREE_PRACTICE: 2,
  FREE_INTERVIEW_LIMIT_MINUTES: 30,
  FREE_MAX_QUESTIONS: 4,
  FREE_PRACTICE_ACCESS_PERCENT: 25,

  PRO_INTERVIEWS: Infinity,
  PRO_PRACTICE: Infinity,
  PRO_INTERVIEW_LIMIT_MINUTES: 60,
  PRO_MAX_QUESTIONS: 10,
  PRO_PRACTICE_ACCESS_PERCENT: 100,
};

export const DEFAULTS = {
  AUTOSAVE_DELAY_MS: 1200,
  MAX_HINT_LEVEL: 3,
};
