export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_PAGE_SIZE: 5,
  MAX_PAGE_SIZE: 100,
  MIN_PAGE_SIZE: 1,

  DASHBOARD_RECENT_PAGE_SIZE: 5,
};

export const LIMITS = {
  FREE_INTERVIEWS: 2,
  FREE_PRACTICE: 2,
  FREE_INTERVIEW_LIMIT_MINUTES: 30,
  FREE_MAX_QUESTIONS: 4,
  FREE_PRACTICE_ACCESS_PERCENT: 25,

  PRO_INTERVIEWS: Infinity,
  PRO_PRACTICE: Infinity,
  PRO_INTERVIEW_LIMIT_MINUTES: 60,
  PRO_MAX_QUESTIONS: 10,
  PRO_PRACTICE_ACCESS_PERCENT: 100,
};

export const DEFAULTS = {
  AUTOSAVE_DELAY_MS: 1200,
  MAX_HINT_LEVEL: 3,
  MAX_POLL_ATTEMPTS: 20,
};

export const RESUME = {
  MAX_FILE_SIZE_BYTES: 5 * 1024 * 1024,
  ALLOWED_MIME_TYPES: ["application/pdf"],
  ALLOWED_EXTENSION: ".pdf",
};

export const AVATAR = {
  MAX_FILE_SIZE_BYTES: 2 * 1024 * 1024,
  ALLOWED_MIME_TYPES: ["image/png", "image/jpeg", "image/svg+xml"],
  ALLOWED_EXTENSIONS: [".png", ".jpg", ".jpeg", ".svg"],
};

export const ACTIVITY = {
  HISTORY_DAYS: 371,
};

export const VIRUS_TOTAL = {
  POLL_INTERVAL_MS: 2000,
  MAX_POLL_ATTEMPTS: 6,
};

export const STORAGE_KEYS = {
  GEMINI_API_KEY: "zach:gemini-api-key",
};

export const GEMINI_KEY_HEADER = "x-gemini-key";

export const RECRUITER_APPLICATION = {
  MIN_DESCRIPTION_LENGTH: 40,
  MAX_DESCRIPTION_LENGTH: 2000,
};

export const RECRUITER_INVITE_QUESTION_COUNT = 3;
